---

- name: Update Ubuntu Server 
  apt: update_cache=true
# - name: Upgrade Ubuntu Server
# - apt: upgrade=yes 
- name: Ensure that libpq-dev, python-setuptools, python-dev, and pip are installed.
  apt: name={{ item }} state=installed
  with_items:
    - libpq-dev
    - python-setuptools 
    - python-dev
    - python-pip

- name: Ensure that the requirements directory exists
  file: path=setup/requirements state=directory
- name: Copy the local pip requirements file 
  copy: src=requirements.txt dest=requirements/requirements
- name: Install python package requirements 
